version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: sivi_design_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: sivi_user
      POSTGRES_PASSWORD: sivi_pass
      POSTGRES_DB: sivi_db
    volumes:
      - sivi_design_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sivi_design_data:
    name: sivi_design_data
