version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: cv_design_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cv_user
      POSTGRES_PASSWORD: cv_pass
      POSTGRES_DB: cv_db
    volumes:
      - cv_design_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cv_design_data:
    name: cv_design_data
